# Generated by Django 4.1.2 on 2022-11-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='is_published',
        ),
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.CharField(default='ARCHIVED', max_length=10),
        ),
    ]
